Repository helmfile/helmfile, pull requests merged in 2023-04, with the labels that each got.

#771 feat: add/expose cli flags
  cmd/apply.go
  cmd/delete.go
  cmd/destroy.go
  cmd/diff.go
  cmd/fetch.go
  cmd/lint.go
  cmd/root.go
  cmd/sync.go
  cmd/template.go
  cmd/test.go
  cmd/write-values.go
  docs/index.md
  pkg/app/app.go
  pkg/app/app_test.go
  pkg/app/config.go
  pkg/app/init.go
  pkg/app/mocks_test.go
  pkg/config/apply.go
  pkg/config/delete.go
  pkg/config/destroy.go
  pkg/config/diff.go
  pkg/config/fetch.go
  pkg/config/global.go
  pkg/config/lint.go
  pkg/config/sync.go
  pkg/config/template.go
  pkg/config/test.go
  pkg/config/write-values.go
  pkg/exectest/helm.go
  pkg/helmexec/exec.go
  pkg/helmexec/exec_test.go
  pkg/helmexec/helmexec.go
Labels: feature, in progress

#787 fix: ValuesTemplate quote issue
  pkg/state/release_test.go
  pkg/yaml/yaml.go
  pkg/yaml/yaml_test.go
Labels: bug

#773 feat: add duration to affected releases on sync
  pkg/app/app_sync_test.go
  pkg/app/destroy_nokubectx_test.go
  pkg/app/destroy_test.go
  pkg/app/testdata/testapply/delete_bar_when_bar_needs_foo/log
  pkg/app/testdata/testapply/delete_bar_when_foo_needs_bar/log
  pkg/app/testdata/testapply/delete_foo_and_bar_when_bar_needs_foo/log
  pkg/app/testdata/testapply/delete_foo_and_bar_when_foo_needs_bar/log
  pkg/app/testdata/testapply/delete_foo_when_bar_needs_foo/log
  pkg/app/testdata/testapply/delete_foo_when_foo_needs_bar/log
  pkg/app/testdata/testapply/install-with-upgrade-with-skip-diff-on-install/log
  pkg/app/testdata/testapply/install-with-upgrade-with-validation-control/log
  pkg/app/testdata/testapply/install/log
  pkg/app/testdata/testapply/smoke/log
  pkg/app/testdata/testapply/upgrade_when_bar_needs_foo,_with_ns_override/log
  pkg/app/testdata/testapply/upgrade_when_bar_needs_foo/log
  pkg/app/testdata/testapply/upgrade_when_foo_needs_bar,_with_ns_override/log
  pkg/app/testdata/testapply/upgrade_when_foo_needs_bar/log
  pkg/app/testdata/testapply/upgrade_when_ns1/foo_needs_ns2/bar/log
  pkg/app/testdata/testapply/upgrade_when_ns2/bar_needs_ns1/foo/log
  pkg/app/testdata/testapply/upgrades_with_good_selector_with_--skip-needs=true/log
  pkg/app/testdata/testapply_2/apply_release_with_preapply_hook/log
  pkg/app/testdata/testapply_2/deduplicate_by_--selector/log
  pkg/app/testdata/testapply_2/include-transitive-needs=true/log
  pkg/app/testdata/testapply_2/select_single_release_from_helmfile_with_two_duplicates/log
  pkg/app/testdata/testapply_2/skip-needs=false_include-needs=true/log
  pkg/app/testdata/testapply_2/skip-needs=false_include-needs=true_but_no_diff_on_needed_release/log
  pkg/app/testdata/testapply_2/skip-needs=false_include-needs=true_with_installed_but_disabled_release/log
  pkg/app/testdata/testapply_2/skip-needs=false_include-needs=true_with_not_installed_and_disabled_release/log
  pkg/app/testdata/testapply_2/skip-needs=true/log
  pkg/app/testdata/testapply_2/skip-needs=true_with_no_diff_on_a_release/log
  pkg/app/testdata/testapply_3/skip-needs=false_include-needs=true/log
  pkg/app/testdata/testapply_3/skip-needs=false_include-needs=true_but_no_diff_on_needed_release/log
  pkg/app/testdata/testapply_3/skip-needs=false_include-needs=true_with_installed_but_disabled_release/log
  pkg/app/testdata/testapply_3/skip-needs=false_include-needs=true_with_not_installed_and_disabled_release/log
  pkg/app/testdata/testapply_3/skip-needs=true/log
  pkg/app/testdata/testapply_3/skip-needs=true_with_no_diff_on_a_release/log
  pkg/app/testdata/testapply_hooks/apply_release_with_preapply_hook#01/log
  pkg/app/testdata/testapply_hooks/apply_release_with_preapply_hook#02/log
  pkg/app/testdata/testapply_hooks/apply_release_with_preapply_hook/log
  pkg/app/testdata/testapply_hooks/hooks_are_not_run_on_alreadyd_uninstalled_release/log
  pkg/app/testdata/testapply_hooks/hooks_are_not_run_on_disabled_release/log
  pkg/app/testdata/testapply_hooks/hooks_are_run_on_enabled_release/log
  pkg/app/testdata/testapply_hooks/hooks_are_run_on_to-be-uninstalled_release/log
  pkg/state/state.go
  pkg/state/temp_test.go
Labels: feature, in progress

#804 Add kube version flag
  cmd/template.go
  pkg/app/app.go
  pkg/app/app_test.go
  pkg/app/config.go
  pkg/config/template.go
  pkg/state/state.go
  pkg/state/state_test.go
Labels: feature, in progress

#750 Make helmfile respect signals send by kill command (not only Ctrl+C in terminal)
  main.go
  pkg/app/app.go
  pkg/event/bus.go
  pkg/helmexec/exec_test.go
  pkg/helmexec/runner.go
  pkg/helmexec/runner_test.go
  pkg/tmpl/context_funcs.go
  test/e2e/template/helmfile/snapshot_test.go
Labels: feature
